
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    lastname TEXT NOT NULL CHECK (lastname <> ''),
    gmail TEXT NOT NULL CHECK (gmail ~* '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cathegory (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cathegory TEXT NOT NULL CHECK (cathegory <> ''),
    userid INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL CHECK (title <> ''),
    content TEXT NOT NULL CHECK (content <> ''),
    cathegoryid INTEGER REFERENCES cathegory(id),
    userid INTEGER REFERENCES users(id),
    archieved BOOLEAN
);
